USE [COMP3851B]
GO

/****** Object:  Table [dbo].[campus]    Script Date: 18/10/2022 12:48:13 pm ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[campus](
	[campusID] [int] IDENTITY(1,1) NOT NULL,
	[campusLoc] [nvarchar](255) NULL,
	[campusImg] [varbinary](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[campusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

