//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace COMP3851B.Views.Admin.CourseGuide
{
    public partial class EditCourseGuide
    {
    }
}
